@startuml
'https://plantuml.com/class-diagram

package ex42{
    class App{
        +{static}listSize(ArrayList<String> list)
        +{static}printData(ArrayList<String> lNames, ArrayList<String> fNames, ArrayList<String> salaries)
        +{static}main(String[] args)
    }
}

@enduml