@startuml
'https://plantuml.com/class-diagram

package ex43{
    class App{
        +{static}makeDirectory (String path)
        +{static}printIfSuccessful (File file, String path)
        +{static}main(String[] args)
    }
}
@enduml